### ISSUE TITLE
Feedback on revamped Zowe.org

### ISSUE THREAD

**Issue by nannanli** [zowe/zowe.github.io#130]
The preview of the revamped site is here https://deploy-preview-121--condescending-dubinsky-4645a9.netlify.app/. Any feedback are appreciated!

**Comment by nannanli** [comment]
Previous comments from Joe:

**Comment by DivergentEuropeans** [comment]
Hey @nannanli Very cool! 
1. I noticed however that the intro video isn't loading correctly for me (I'm guessing this is where Joe's new video should be?)
http://prntscr.com/10sop5b
Just making sure this is intended to be broken due to preview mode or something

2. At https://deploy-preview-121--condescending-dubinsky-4645a9.netlify.app/extend I noticed,
"3. Add a plug-in to the Zowe Desktop."
I'd recommend changing this to,
"3. Add a plug-in (or "app") to the Zowe Desktop."

3. At https://deploy-preview-121--condescending-dubinsky-4645a9.netlify.app/extend
Below "Getting a Zowe Conformance Badge happens in 3 steps:" exist 3 buttons, the first button correctly points to the TOS,
however the 2nd and 3rd button do not point to the Test Evaluation Guide and Participation Form, though the links for both of these are included a page down in the TOS

4. Totally love the "Connect on Slack" idea

5. I love the component consolidation on the website. Image assets look better, cleaner, more optimized. I propose adding a 3rd option, the two below each component "Code on GitHub" shows repositories that house the core coding portions of those components "Learn more" sends to a GitHub link that is incredibly informative, but very detailed and maybe somewhat overwhelming at first glance, I suggest adding a 3rd option, which makes the titles of the components themselves that point to their slightly more verbose introductions in the Docs. For example, "Zowe Application Framework" title would hyperlink to

https://docs.zowe.org/stable/getting-started/overview.html#zowe-application-framework

Overall, a good look and great job to all involved in the revamp 🍨

**Comment by DivergentEuropeans** [comment]
@nannanli  Update: I think the Zowe YouTube video not showing up may be a personal issue with my work VPN. Check it out just in-case, but that's probably just my own things conflicting 🙂

**Comment by nannanli** [comment]
@DivergentEuropeans Thanks for the update! I'll find more folks to test this video in different browsers and OS to ensure that it's not a common issue.

**Comment by nannanli** [comment]
@DivergentEuropeans @Joe-Winchester All the comments have been incorporated. Check out the updated design and let us know if any issue persists!   
https://deploy-preview-121--condescending-dubinsky-4645a9.netlify.app/

**Comment by covalentbond** [comment]
Thanks @RASakach for the feedback. The upcoming events are actually planned to be automatically sync with OMP website [Zowe events section](https://www.openmainframeproject.org/events/category/zowe). This auto sync functionality might only work once the [PR](https://github.com/zowe/zowe.github.io/pull/121) is merged. So that we will not need to manually update the events and it will also remove the past events automatically.

For now, I've updated the events manually.

About the Announcements banner, yes we can look for some ways to improve. Let me know if doing something like this might solve the issue:

![image](https://user-images.githubusercontent.com/53327173/113179881-b45cc000-926d-11eb-8776-e27e79c8d613.png)

**Comment by RASakach** [comment]
@covalentbond - I like what you've done with the Announcements!  Simple, but it achieves the goal!

The UPCOMING EVENTS change, did not fix, in fact we've lost 2 other events that were listed on that page.  :-(  I think you can revert to how it looked prior - I've put in a request to Mae to fix the underlying event information.

Finally - one more piece of feedback - on the STATS information listed on the landing page.  The Onboarding Squad just reviewed them @Joe-Winchester , Mike Dubois - and we agreed that the links for some of those items should be revised to point to the underlying DATA - specifically the links that take the user to the DOWNLOAD page let us know how best to get these corrected - should we provide you with the proper links here?  Thanks again!

**Comment by covalentbond** [comment]
Currently the events auto sync feature only seem to return the upcoming events and thus removed all the past events which have already occured. Similar to how it's being shown on [OMP Website upcoming events](https://www.openmainframeproject.org/events/category/zowe) for Zowe.

![image](https://user-images.githubusercontent.com/53327173/113197167-f4c63900-9281-11eb-8f9a-bc433578ef0c.png)

If we do want to show the past events as well like it was prior shown. I might need to ask @jmertic regarding a new ICalendar response, which returns the past events as well. Otherwise we might need to remove the auto sync feature, and manually add events. Since the current iCalendar only returns the upcoming events, not the past

Yes, it will be great if can provide some of the revised links for the stats section.

**Comment by covalentbond** [comment]
hey @jmertic, currently the ICS feed provided by you (https://www.openmainframeproject.org/events/category/zowe?ical=1&tribe_display=photo) only seem to return the upcoming events. So once the script run, it removes all the past events as well. Is there any way we can get the past events as well in the ICS response. We might overall need to show the latest three events.

**Comment by jmertic** [comment]
@covalentbond There is another ICS feed for past events at https://www.openmainframeproject.org/events/category/zowe?action=tribe_photo&tribe_paged=1&tribe_event_display=past&tribe-bar-date=2021-03-31&ical=1&tribe_display=past

**Comment by covalentbond** [comment]
@jmertic thanks, can you re-check once. It does'nt seem to provide the response with events in it.

**Comment by covalentbond** [comment]
@jmertic thanks, can you re-check once. It doesn't seem to provide the response with events in it.

**Comment by nannanli** [comment]
@RASakach Hi Rose, thanks for the feedback! For the links on STATS section, please send the links to @covalentbond and me. We'll fix them accordingly. Many thanks!

**Comment by jmertic** [comment]
> @jmertic thanks, can you re-check once. It doesn't seem to provide the response with events in it.

Whoops! Try https://www.openmainframeproject.org/events/category/zowe?action=tribe_photo&tribe_paged=1&tribe_event_display=past&tribe-bar-date=2021-03-31&ical=1&tribe_display=past&ical=1

**Comment by covalentbond** [comment]
No sir, it doesn't show any response with events in it. Tried both date formats `2021-04-01` & `2021-04-1`. As you may find in the below image:

![image](https://user-images.githubusercontent.com/53327173/113283485-fe918000-9305-11eb-818a-d2c617338a9a.png)

Also downloading the ICS file shows `The file does not contain any appointments.`

**Comment by jmertic** [comment]
Hmm - I see that too. It seems removing the date helps...

https://www.openmainframeproject.org/events/category/zowe?action=tribe_photo&tribe_paged=1&tribe_event_display=past&ical=1&tribe_display=past

**Comment by covalentbond** [comment]
thanks, it worked and I modified the [script](https://github.com/covalentbond/zowe.github.io/blob/version2.0/assets/script/ics-to-yml.py) accordingly

**Comment by DivergentEuropeans** [comment]
@covalentbond @nannanli Additionally, if possible to this section,
![image](https://user-images.githubusercontent.com/20528015/113307153-d3da0400-92d2-11eb-9e6f-25412b1c82e7.png)
I'd like to add another option 
![image](https://user-images.githubusercontent.com/20528015/113307331-0552cf80-92d3-11eb-97ae-368a8744dd15.png)

which points to our OMP, full-length Virtual Desktop & core Application Framework apps showcase:
https://www.youtube.com/watch?v=cbEVbcsaGCs&ab_channel=OpenMainframeProject

**Comment by covalentbond** [comment]
@DivergentEuropeans added it, let us know if you have any other suggestions!

**Comment by DivergentEuropeans** [comment]
> @DivergentEuropeans added it, let us know if you have any other suggestions!

Perfect 👍

**Comment by RASakach** [comment]
Hi @covalentbond and @nannanli - for the ZOWE BY THE NUMBERS link update.  Please use this link: [https://www.metrics.zowe.org/](https://www.metrics.zowe.org/) 
1.  When the user hovers over the title  "ZOWE BY THE NUMBERS" 
2.  When the user hovers over "Zowe CLI Downloads" 
3. When the user hovers over "Zowe z/OS Build Downloads"

All of the other links can stay.

**Comment by nannanli** [comment]
@RASakach The links have been updated. Check it out https://deploy-preview-121--condescending-dubinsky-4645a9.netlify.app/.  : )

**Comment by RASakach** [comment]
@covalentbond & @nannanli :  One more small request - please modify this section title: Upcoming events

Change it to read "Upcoming and Recent Events"

[this way we can showcase items that are technically in the past].

Thank you very much!  This is amazing!  Also, let us know when you'd like to go LIVE.

**Comment by MikeBauerCA** [comment]
We would like the Zowe CLI component section to also bring visibility to our CLI plug-ins and link to them on GitHub:
[Secure Credential Store Plug-in for Zowe CLI](https://github.com/zowe/zowe-cli-scs-plugin)
[CICS Plug-in for Zowe CLI](https://github.com/zowe/zowe-cli-cics-plugin)
[Db2 Plug-in for Zowe CLI](https://github.com/zowe/zowe-cli-db2-plugin)
[FTP Plug-in for Zowe CLI](https://github.com/zowe/zowe-cli-ftp-plugin)
[IMS Plug-in for Zowe CLI](https://github.com/zowe/zowe-cli-ims-plugin)
[MQ Plug-in for Zowe CLI](https://github.com/zowe/zowe-cli-mq-plugin)

We would also like the Zowe SDK to link to the specific SDK repos:
[Node SDK](https://github.com/zowe/zowe-cli)
[Python SDK](https://github.com/zowe/zowe-client-python-sdk)
[Swift SDK](https://github.com/zowe/zowe-client-swift-sdk)

Lastly, please replace the Java logo with the Swift logo in the Zowe SDK section and mention Swift in the text. Hopefully we have a Java SDK in the future :)

**Comment by covalentbond** [comment]
Thanks @MikeBauerCA ! You can check it now, your changes have been incorporated [here](https://deploy-preview-121--condescending-dubinsky-4645a9.netlify.app/).

Let us know, if you have any other suggestions.

**Comment by MikeBauerCA** [comment]
Thanks! You are fast 🏁 

For the SDK piece, the Node SDK link and the Code on GitHub link are to the same place. Do you think we should keep both, or remove the "Code on GitHub" link?
![image](https://user-images.githubusercontent.com/35504792/114091266-74599680-9886-11eb-901a-baed0c3716e4.png)

**Comment by covalentbond** [comment]
Yes, it does make sense to remove it!

**Comment by nannanli** [comment]
All feedback have been incorporated. TSC has approved the publish of the site. See Slack voting thread: https://openmainframeproject.slack.com/archives/C01H6CY0ZD1/p1617979518034600
