### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe.github.io#307]
https://www.zowe.org/legal.html?version=1.25.0 contains a link to TPSR https://docs.zowe.org/stable/appendix/tpsr.html
This link goes nowhere. It must have moved, but we need to fix it for license reasons.

Source page to update: 
https://github.com/zowe/zowe.github.io/blob/master/legal.md

**Comment by nannanli** [comment]
Assigned to @samanthasusu

**Comment by nannanli** [comment]
The TPSR files have been converted into Markdown format and stored in the following folder due to its large size in being converted to HTML. 
https://github.com/zowe/docs-site/tree/master/tpsr

Each release has a corresponding TPSR file but in the current legal.html file, regardless of the Zowe build version being downloaded, it always points people to the latest release TPSR by referring to /stable/TPSR.html. I think we intend to provide release-specific TPSR. So when for v1.26 release, the link on the legal.html page should point to `https://github.com/zowe/docs-site/blob/master/tpsr/tpsr-v1.26.x.md`. @MarkAckert @FlappiTomic @1000TurquoisePogs  Just want to confirm whether this is true. Thanks!

**Comment by 1000TurquoisePogs** [comment]
It sounds fine to me to link the md file. I believe fixing the link is a legal requirement and which format it resolves to is not as important.

**Comment by nannanli** [comment]
This has been fixed. Closing.
